import {Dimensions, Platform, StyleSheet} from 'react-native';
import {moderateScale} from '../utils/orientation';

export const width = Dimensions.get('screen').width;
export const height = Dimensions.get('screen').height;

const Css = StyleSheet.create({
  br0: {
    borderRadius: moderateScale(0),
  },
  br5: {
    borderRadius: moderateScale(5),
  },
  br10: {
    borderRadius: moderateScale(10),
  },
  br15: {
    borderRadius: moderateScale(15),
  },
  br20: {
    borderRadius: moderateScale(20),
  },
  br25: {
    borderRadius: moderateScale(25),
  },
  br30: {
    borderRadius: moderateScale(30),
  },
  br35: {
    borderRadius: moderateScale(35),
  },

  bsbottom: {
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    shadowColor: '#D9C0E54D',
    elevation: 5,
  },

  op0: {opacity: 0},
  op05: {opacity: 0.5},
  op1: {opacity: 1},

  f1: {flex: 1},
  fg1: {flexGrow: 1},
  tac: {textAlign: 'center'},
  tal: {textAlign: 'left'},
  tar: {textAlign: 'right'},
  taj: {textAlign: 'justify'},
  fw: {flexWrap: 'wrap'},
  ofh: {overflow: 'hidden'},
  bgRed: {backgroundColor: 'red'},
  bgYellow: {backgroundColor: 'yellow'},
  bgGreen: {backgroundColor: 'green'},
  asc: {alignSelf: 'center'},
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  posabsolute: {position: 'absolute'},
  posrelative: {position: 'relative'},
  posstatic: {position: 'static'},

  ttc: {textTransform: 'capitalize'},
  ttl: {textTransform: 'lowercase'},
  ttn: {textTransform: 'none'},
  ttu: {textTransform: 'uppercase'},

  g0: {gap: 0},
  g1: {gap: moderateScale(2)},
  g2: {gap: moderateScale(4)},
  g3: {gap: moderateScale(6)},
  g4: {gap: moderateScale(8)},
  g5: {gap: moderateScale(10)},
  g6: {gap: moderateScale(12)},
  g7: {gap: moderateScale(14)},
  g8: {gap: moderateScale(16)},
  g9: {gap: moderateScale(18)},
  g10: {gap: moderateScale(20)},
  g11: {gap: moderateScale(22)},
  g12: {gap: moderateScale(24)},
  g13: {gap: moderateScale(26)},
  g14: {gap: moderateScale(28)},
  g15: {gap: moderateScale(30)},
  g16: {gap: moderateScale(32)},
  g17: {gap: moderateScale(34)},
  g18: {gap: moderateScale(36)},
  g19: {gap: moderateScale(38)},
  g20: {gap: moderateScale(40)},
  g21: {gap: moderateScale(42)},
  g22: {gap: moderateScale(44)},
  g23: {gap: moderateScale(46)},
  g24: {gap: moderateScale(48)},
  g25: {gap: moderateScale(50)},

  m0: {margin: 0},
  m1: {margin: moderateScale(2)},
  m2: {margin: moderateScale(4)},
  m3: {margin: moderateScale(6)},
  m4: {margin: moderateScale(8)},
  m5: {margin: moderateScale(10)},
  m6: {margin: moderateScale(12)},
  m7: {margin: moderateScale(14)},
  m8: {margin: moderateScale(16)},
  m9: {margin: moderateScale(18)},
  m10: {margin: moderateScale(20)},
  m11: {margin: moderateScale(22)},
  m12: {margin: moderateScale(24)},
  m13: {margin: moderateScale(26)},
  m14: {margin: moderateScale(28)},
  m15: {margin: moderateScale(30)},
  m16: {margin: moderateScale(32)},
  m17: {margin: moderateScale(34)},
  m18: {margin: moderateScale(36)},
  m19: {margin: moderateScale(38)},
  m20: {margin: moderateScale(40)},
  m21: {margin: moderateScale(42)},
  m22: {margin: moderateScale(44)},
  m23: {margin: moderateScale(46)},
  m24: {margin: moderateScale(48)},
  m25: {margin: moderateScale(50)},

  mx0: {marginHorizontal: 0},
  mx1: {marginHorizontal: moderateScale(2)},
  mx2: {marginHorizontal: moderateScale(4)},
  mx3: {marginHorizontal: moderateScale(6)},
  mx4: {marginHorizontal: moderateScale(8)},
  mx5: {marginHorizontal: moderateScale(10)},
  mx6: {marginHorizontal: moderateScale(12)},
  mx7: {marginHorizontal: moderateScale(14)},
  mx8: {marginHorizontal: moderateScale(16)},
  mx9: {marginHorizontal: moderateScale(18)},
  mx10: {marginHorizontal: moderateScale(20)},
  mx11: {marginHorizontal: moderateScale(22)},
  mx12: {marginHorizontal: moderateScale(24)},
  mx13: {marginHorizontal: moderateScale(26)},
  mx14: {marginHorizontal: moderateScale(28)},
  mx15: {marginHorizontal: moderateScale(30)},
  mx16: {marginHorizontal: moderateScale(32)},
  mx17: {marginHorizontal: moderateScale(34)},
  mx18: {marginHorizontal: moderateScale(36)},
  mx19: {marginHorizontal: moderateScale(38)},
  mx20: {marginHorizontal: moderateScale(40)},
  mx21: {marginHorizontal: moderateScale(42)},
  mx22: {marginHorizontal: moderateScale(44)},
  mx23: {marginHorizontal: moderateScale(46)},
  mx24: {marginHorizontal: moderateScale(48)},
  mx25: {marginHorizontal: moderateScale(50)},

  my0: {marginVertical: 0},
  my1: {marginVertical: moderateScale(2)},
  my2: {marginVertical: moderateScale(4)},
  my3: {marginVertical: moderateScale(6)},
  my4: {marginVertical: moderateScale(8)},
  my5: {marginVertical: moderateScale(10)},
  my6: {marginVertical: moderateScale(12)},
  my7: {marginVertical: moderateScale(14)},
  my8: {marginVertical: moderateScale(16)},
  my9: {marginVertical: moderateScale(18)},
  my10: {marginVertical: moderateScale(20)},
  my11: {marginVertical: moderateScale(22)},
  my12: {marginVertical: moderateScale(24)},
  my13: {marginVertical: moderateScale(26)},
  my14: {marginVertical: moderateScale(28)},
  my15: {marginVertical: moderateScale(30)},
  my16: {marginVertical: moderateScale(32)},
  my17: {marginVertical: moderateScale(34)},
  my18: {marginVertical: moderateScale(36)},
  my19: {marginVertical: moderateScale(38)},
  my20: {marginVertical: moderateScale(40)},
  my21: {marginVertical: moderateScale(42)},
  my22: {marginVertical: moderateScale(44)},
  my23: {marginVertical: moderateScale(46)},
  my24: {marginVertical: moderateScale(48)},
  my25: {marginVertical: moderateScale(50)},

  ml0: {marginLeft: 0},
  ml1: {marginLeft: moderateScale(2)},
  ml2: {marginLeft: moderateScale(4)},
  ml3: {marginLeft: moderateScale(6)},
  ml4: {marginLeft: moderateScale(8)},
  ml5: {marginLeft: moderateScale(10)},
  ml6: {marginLeft: moderateScale(12)},
  ml7: {marginLeft: moderateScale(14)},
  ml8: {marginLeft: moderateScale(16)},
  ml9: {marginLeft: moderateScale(18)},
  ml10: {marginLeft: moderateScale(20)},
  ml11: {marginLeft: moderateScale(22)},
  ml12: {marginLeft: moderateScale(24)},
  ml13: {marginLeft: moderateScale(26)},
  ml14: {marginLeft: moderateScale(28)},
  ml15: {marginLeft: moderateScale(30)},
  ml16: {marginLeft: moderateScale(32)},
  ml17: {marginLeft: moderateScale(34)},
  ml18: {marginLeft: moderateScale(36)},
  ml19: {marginLeft: moderateScale(38)},
  ml20: {marginLeft: moderateScale(40)},
  ml21: {marginLeft: moderateScale(42)},
  ml22: {marginLeft: moderateScale(44)},
  ml23: {marginLeft: moderateScale(46)},
  ml24: {marginLeft: moderateScale(48)},
  ml25: {marginLeft: moderateScale(50)},

  mr0: {marginRight: 0},
  mr1: {marginRight: moderateScale(2)},
  mr2: {marginRight: moderateScale(4)},
  mr3: {marginRight: moderateScale(6)},
  mr4: {marginRight: moderateScale(8)},
  mr5: {marginRight: moderateScale(10)},
  mr6: {marginRight: moderateScale(12)},
  mr7: {marginRight: moderateScale(14)},
  mr8: {marginRight: moderateScale(16)},
  mr9: {marginRight: moderateScale(18)},
  mr10: {marginRight: moderateScale(20)},
  mr11: {marginRight: moderateScale(22)},
  mr12: {marginRight: moderateScale(24)},
  mr13: {marginRight: moderateScale(26)},
  mr14: {marginRight: moderateScale(28)},
  mr15: {marginRight: moderateScale(30)},
  mr16: {marginRight: moderateScale(32)},
  mr17: {marginRight: moderateScale(34)},
  mr18: {marginRight: moderateScale(36)},
  mr19: {marginRight: moderateScale(38)},
  mr20: {marginRight: moderateScale(40)},
  mr21: {marginRight: moderateScale(42)},
  mr22: {marginRight: moderateScale(44)},
  mr23: {marginRight: moderateScale(46)},
  mr24: {marginRight: moderateScale(48)},
  mr25: {marginRight: moderateScale(50)},

  mt0: {marginTop: 0},
  mt1: {marginTop: moderateScale(2)},
  mt2: {marginTop: moderateScale(4)},
  mt3: {marginTop: moderateScale(6)},
  mt4: {marginTop: moderateScale(8)},
  mt5: {marginTop: moderateScale(10)},
  mt6: {marginTop: moderateScale(12)},
  mt7: {marginTop: moderateScale(14)},
  mt8: {marginTop: moderateScale(16)},
  mt9: {marginTop: moderateScale(18)},
  mt10: {marginTop: moderateScale(20)},
  mt11: {marginTop: moderateScale(22)},
  mt12: {marginTop: moderateScale(24)},
  mt13: {marginTop: moderateScale(26)},
  mt14: {marginTop: moderateScale(28)},
  mt15: {marginTop: moderateScale(30)},
  mt16: {marginTop: moderateScale(32)},
  mt17: {marginTop: moderateScale(34)},
  mt18: {marginTop: moderateScale(36)},
  mt19: {marginTop: moderateScale(38)},
  mt20: {marginTop: moderateScale(40)},
  mt21: {marginTop: moderateScale(42)},
  mt22: {marginTop: moderateScale(44)},
  mt23: {marginTop: moderateScale(46)},
  mt24: {marginTop: moderateScale(48)},
  mt25: {marginTop: moderateScale(50)},

  mb0: {marginBottom: 0},
  mb1: {marginBottom: moderateScale(2)},
  mb2: {marginBottom: moderateScale(4)},
  mb3: {marginBottom: moderateScale(6)},
  mb4: {marginBottom: moderateScale(8)},
  mb5: {marginBottom: moderateScale(10)},
  mb6: {marginBottom: moderateScale(12)},
  mb7: {marginBottom: moderateScale(14)},
  mb8: {marginBottom: moderateScale(16)},
  mb9: {marginBottom: moderateScale(18)},
  mb10: {marginBottom: moderateScale(20)},
  mb11: {marginBottom: moderateScale(22)},
  mb12: {marginBottom: moderateScale(24)},
  mb13: {marginBottom: moderateScale(26)},
  mb14: {marginBottom: moderateScale(28)},
  mb15: {marginBottom: moderateScale(30)},
  mb16: {marginBottom: moderateScale(32)},
  mb17: {marginBottom: moderateScale(34)},
  mb18: {marginBottom: moderateScale(36)},
  mb19: {marginBottom: moderateScale(38)},
  mb20: {marginBottom: moderateScale(40)},
  mb21: {marginBottom: moderateScale(42)},
  mb22: {marginBottom: moderateScale(44)},
  mb23: {marginBottom: moderateScale(46)},
  mb24: {marginBottom: moderateScale(48)},
  mb25: {marginBottom: moderateScale(50)},
  mbTab: {
    marginBottom:
      Platform.OS === 'ios' ? moderateScale(130) : moderateScale(110),
  },

  p0: {padding: 0},
  p1: {padding: moderateScale(2)},
  p2: {padding: moderateScale(4)},
  p3: {padding: moderateScale(6)},
  p4: {padding: moderateScale(8)},
  p5: {padding: moderateScale(10)},
  p6: {padding: moderateScale(12)},
  p7: {padding: moderateScale(14)},
  p8: {padding: moderateScale(16)},
  p9: {padding: moderateScale(18)},
  p10: {padding: moderateScale(20)},
  p11: {padding: moderateScale(22)},
  p12: {padding: moderateScale(24)},
  p13: {padding: moderateScale(26)},
  p14: {padding: moderateScale(28)},
  p15: {padding: moderateScale(30)},
  p16: {padding: moderateScale(32)},
  p17: {padding: moderateScale(34)},
  p18: {padding: moderateScale(36)},
  p19: {padding: moderateScale(38)},
  p20: {padding: moderateScale(40)},
  p21: {padding: moderateScale(42)},
  p22: {padding: moderateScale(44)},
  p23: {padding: moderateScale(46)},
  p24: {padding: moderateScale(48)},
  p25: {padding: moderateScale(50)},

  pb0: {paddingBottom: 0},
  pb1: {paddingBottom: moderateScale(2)},
  pb2: {paddingBottom: moderateScale(4)},
  pb3: {paddingBottom: moderateScale(6)},
  pb4: {paddingBottom: moderateScale(8)},
  pb5: {paddingBottom: moderateScale(10)},
  pb6: {paddingBottom: moderateScale(12)},
  pb7: {paddingBottom: moderateScale(14)},
  pb8: {paddingBottom: moderateScale(16)},
  pb9: {paddingBottom: moderateScale(18)},
  pb10: {paddingBottom: moderateScale(20)},
  pb11: {paddingBottom: moderateScale(22)},
  pb12: {paddingBottom: moderateScale(24)},
  pb13: {paddingBottom: moderateScale(26)},
  pb14: {paddingBottom: moderateScale(28)},
  pb15: {paddingBottom: moderateScale(30)},
  pb16: {paddingBottom: moderateScale(32)},
  pb17: {paddingBottom: moderateScale(34)},
  pb18: {paddingBottom: moderateScale(36)},
  pb19: {paddingBottom: moderateScale(38)},
  pb20: {paddingBottom: moderateScale(40)},
  pb21: {paddingBottom: moderateScale(42)},
  pb22: {paddingBottom: moderateScale(44)},
  pb23: {paddingBottom: moderateScale(46)},
  pb24: {paddingBottom: moderateScale(48)},
  pb25: {paddingBottom: moderateScale(50)},

  pt0: {paddingTop: 0},
  pt1: {paddingTop: moderateScale(2)},
  pt2: {paddingTop: moderateScale(4)},
  pt3: {paddingTop: moderateScale(6)},
  pt4: {paddingTop: moderateScale(8)},
  pt5: {paddingTop: moderateScale(10)},
  pt6: {paddingTop: moderateScale(12)},
  pt7: {paddingTop: moderateScale(14)},
  pt8: {paddingTop: moderateScale(16)},
  pt9: {paddingTop: moderateScale(18)},
  pt10: {paddingTop: moderateScale(20)},
  pt11: {paddingTop: moderateScale(22)},
  pt12: {paddingTop: moderateScale(24)},
  pt13: {paddingTop: moderateScale(26)},
  pt14: {paddingTop: moderateScale(28)},
  pt15: {paddingTop: moderateScale(30)},
  pt16: {paddingTop: moderateScale(32)},
  pt17: {paddingTop: moderateScale(34)},
  pt18: {paddingTop: moderateScale(36)},
  pt19: {paddingTop: moderateScale(38)},
  pt20: {paddingTop: moderateScale(40)},
  pt21: {paddingTop: moderateScale(42)},
  pt22: {paddingTop: moderateScale(44)},
  pt23: {paddingTop: moderateScale(46)},
  pt24: {paddingTop: moderateScale(48)},
  pt25: {paddingTop: moderateScale(50)},

  px0: {paddingHorizontal: 0},
  px1: {paddingHorizontal: moderateScale(2)},
  px2: {paddingHorizontal: moderateScale(4)},
  px3: {paddingHorizontal: moderateScale(6)},
  px4: {paddingHorizontal: moderateScale(8)},
  px5: {paddingHorizontal: moderateScale(10)},
  px6: {paddingHorizontal: moderateScale(12)},
  px7: {paddingHorizontal: moderateScale(14)},
  px8: {paddingHorizontal: moderateScale(16)},
  px9: {paddingHorizontal: moderateScale(18)},
  px10: {paddingHorizontal: moderateScale(20)},
  px11: {paddingHorizontal: moderateScale(22)},
  px12: {paddingHorizontal: moderateScale(24)},
  px13: {paddingHorizontal: moderateScale(26)},
  px14: {paddingHorizontal: moderateScale(28)},
  px15: {paddingHorizontal: moderateScale(30)},
  px16: {paddingHorizontal: moderateScale(32)},
  px17: {paddingHorizontal: moderateScale(34)},
  px18: {paddingHorizontal: moderateScale(36)},
  px19: {paddingHorizontal: moderateScale(38)},
  px20: {paddingHorizontal: moderateScale(40)},
  px21: {paddingHorizontal: moderateScale(42)},
  px22: {paddingHorizontal: moderateScale(44)},
  px23: {paddingHorizontal: moderateScale(46)},
  px24: {paddingHorizontal: moderateScale(48)},
  px25: {paddingHorizontal: moderateScale(50)},

  py0: {paddingVertical: 0},
  py1: {paddingVertical: moderateScale(2)},
  py2: {paddingVertical: moderateScale(4)},
  py3: {paddingVertical: moderateScale(6)},
  py4: {paddingVertical: moderateScale(8)},
  py5: {paddingVertical: moderateScale(10)},
  py6: {paddingVertical: moderateScale(12)},
  py7: {paddingVertical: moderateScale(14)},
  py8: {paddingVertical: moderateScale(16)},
  py9: {paddingVertical: moderateScale(18)},
  py10: {paddingVertical: moderateScale(20)},
  py11: {paddingVertical: moderateScale(22)},
  py12: {paddingVertical: moderateScale(24)},
  py13: {paddingVertical: moderateScale(26)},
  py14: {paddingVertical: moderateScale(28)},
  py15: {paddingVertical: moderateScale(30)},
  py16: {paddingVertical: moderateScale(32)},
  py17: {paddingVertical: moderateScale(34)},
  py18: {paddingVertical: moderateScale(36)},
  py19: {paddingVertical: moderateScale(38)},
  py20: {paddingVertical: moderateScale(40)},
  py21: {paddingVertical: moderateScale(42)},
  py22: {paddingVertical: moderateScale(44)},
  py23: {paddingVertical: moderateScale(46)},
  py24: {paddingVertical: moderateScale(48)},
  py25: {paddingVertical: moderateScale(50)},

  pl0: {paddingLeft: 0},
  pl1: {paddingLeft: moderateScale(2)},
  pl2: {paddingLeft: moderateScale(4)},
  pl3: {paddingLeft: moderateScale(6)},
  pl4: {paddingLeft: moderateScale(8)},
  pl5: {paddingLeft: moderateScale(10)},
  pl6: {paddingLeft: moderateScale(12)},
  pl7: {paddingLeft: moderateScale(14)},
  pl8: {paddingLeft: moderateScale(16)},
  pl9: {paddingLeft: moderateScale(18)},
  pl10: {paddingLeft: moderateScale(20)},
  pl11: {paddingLeft: moderateScale(22)},
  pl12: {paddingLeft: moderateScale(24)},
  pl13: {paddingLeft: moderateScale(26)},
  pl14: {paddingLeft: moderateScale(28)},
  pl15: {paddingLeft: moderateScale(30)},
  pl16: {paddingLeft: moderateScale(32)},
  pl17: {paddingLeft: moderateScale(34)},
  pl18: {paddingLeft: moderateScale(36)},
  pl19: {paddingLeft: moderateScale(38)},
  pl20: {paddingLeft: moderateScale(40)},
  pl21: {paddingLeft: moderateScale(42)},
  pl22: {paddingLeft: moderateScale(44)},
  pl23: {paddingLeft: moderateScale(46)},
  pl24: {paddingLeft: moderateScale(48)},
  pl25: {paddingLeft: moderateScale(50)},

  pr0: {paddingRight: 0},
  pr1: {paddingRight: moderateScale(2)},
  pr2: {paddingRight: moderateScale(4)},
  pr3: {paddingRight: moderateScale(6)},
  pr4: {paddingRight: moderateScale(8)},
  pr5: {paddingRight: moderateScale(10)},
  pr6: {paddingRight: moderateScale(12)},
  pr7: {paddingRight: moderateScale(14)},
  pr8: {paddingRight: moderateScale(16)},
  pr9: {paddingRight: moderateScale(18)},
  pr10: {paddingRight: moderateScale(20)},
  pr11: {paddingRight: moderateScale(22)},
  pr12: {paddingRight: moderateScale(24)},
  pr13: {paddingRight: moderateScale(26)},
  pr14: {paddingRight: moderateScale(28)},
  pr15: {paddingRight: moderateScale(30)},
  pr16: {paddingRight: moderateScale(32)},
  pr17: {paddingRight: moderateScale(34)},
  pr18: {paddingRight: moderateScale(36)},
  pr19: {paddingRight: moderateScale(38)},
  pr20: {paddingRight: moderateScale(40)},
  pr21: {paddingRight: moderateScale(42)},
  pr22: {paddingRight: moderateScale(44)},
  pr23: {paddingRight: moderateScale(46)},
  pr24: {paddingRight: moderateScale(48)},
  pr25: {paddingRight: moderateScale(50)},

  fs11: {fontSize: 11},
  fs12: {fontSize: 12},
  fs13: {fontSize: 13},
  fs14: {fontSize: 14},
  fs15: {fontSize: 15},
  fs16: {fontSize: 16},
  fs17: {fontSize: 17},
  fs18: {fontSize: 18},
  fs19: {fontSize: 19},
  fs20: {fontSize: 20},
  fs21: {fontSize: 21},
  fs22: {fontSize: 22},
  fs23: {fontSize: 23},
  fs24: {fontSize: 24},
  fs25: {fontSize: 25},
  fs26: {fontSize: 26},
  fs27: {fontSize: 27},
  fs28: {fontSize: 28},
  fs29: {fontSize: 29},
  fs30: {fontSize: 30},
  fs31: {fontSize: 31},
  fs32: {fontSize: 32},
  fs33: {fontSize: 33},
  fs34: {fontSize: 34},
  fs35: {fontSize: 35},
  fs36: {fontSize: 36},
  fs37: {fontSize: 37},
  fs38: {fontSize: 38},
  fs39: {fontSize: 39},
  fs40: {fontSize: 40},
  fs41: {fontSize: 41},
  fs42: {fontSize: 42},
  fs43: {fontSize: 43},
  fs44: {fontSize: 44},
  fs45: {fontSize: 45},
  fs46: {fontSize: 46},
  fs47: {fontSize: 47},
  fs48: {fontSize: 48},
  fs49: {fontSize: 49},
  fs50: {fontSize: 50},

  wAuto: {width: 'auto'},
  w10: {width: '10%'},
  w20: {width: '20%'},
  w25: {width: '25%'},
  w30: {width: '30%'},
  w33: {width: '33%'},
  w35: {width: '35%'},
  w40: {width: '40%'},
  w45: {width: '45%'},
  w47: {width: '47.5%'},
  w50: {width: '50%'},
  w55: {width: '55%'},
  w60: {width: '60%'},
  w65: {width: '65%'},
  w70: {width: '70%'},
  w75: {width: '75%'},
  w78: {width: '78%'},
  w80: {width: '80%'},
  w85: {width: '85%'},
  w90: {width: '90%'},
  w95: {width: '95%'},
  w100: {width: '100%'},

  minW10: {minWidth: '10%'},
  minW20: {minWidth: '20%'},
  minW25: {minWidth: '25%'},
  minW30: {minWidth: '30%'},
  minW33: {minWidth: '33%'},
  minW40: {minWidth: '40%'},
  minW47: {minWidth: '47.5%'},
  minW50: {minWidth: '50%'},
  minW60: {minWidth: '60%'},
  minW65: {minWidth: '65%'},
  minW70: {minWidth: '70%'},
  minW75: {minWidth: '75%'},
  minW80: {minWidth: '80%'},
  minW85: {minWidth: '85%'},
  minW90: {minWidth: '90%'},
  minW100: {minWidth: '100%'},

  maxW10: {maxWidth: '10%'},
  maxW20: {maxWidth: '20%'},
  maxW25: {maxWidth: '25%'},
  maxW30: {maxWidth: '30%'},
  maxW33: {maxWidth: '33%'},
  maxW40: {maxWidth: '40%'},
  maxW47: {maxWidth: '47.5%'},
  maxW50: {maxWidth: '50%'},
  maxW60: {maxWidth: '60%'},
  maxW65: {maxWidth: '65%'},
  maxW70: {maxWidth: '70%'},
  maxW75: {maxWidth: '75%'},
  maxW80: {maxWidth: '80%'},
  maxW85: {maxWidth: '85%'},
  maxW90: {maxWidth: '90%'},
  maxW100: {maxWidth: '100%'},

  hAuto: {height: 'auto'},
  h10: {height: '10%'},
  h20: {height: '20%'},
  h25: {height: '25%'},
  h30: {height: '30%'},
  h33: {height: '33%'},
  h40: {height: '40%'},
  h50: {height: '50%'},
  h60: {height: '60%'},
  h70: {height: '70%'},
  h80: {height: '80%'},
  h90: {height: '90%'},
  h100: {height: '100%'},

  minH10: {minHeight: '10%'},
  minH20: {minHeight: '20%'},
  minH25: {minHeight: '25%'},
  minH30: {minHeight: '30%'},
  minH33: {minHeight: '33%'},
  minH40: {minHeight: '40%'},
  minH47: {minHeight: '47.5%'},
  minH50: {minHeight: '50%'},
  minH60: {minHeight: '60%'},
  minH65: {minHeight: '65%'},
  minH70: {minHeight: '70%'},
  minH75: {minHeight: '75%'},
  minH80: {minHeight: '80%'},
  minH85: {minHeight: '85%'},
  minH90: {minHeight: '90%'},
  minH100: {minHeight: '100%'},

  maxH10: {maxHeight: '10%'},
  maxH20: {maxHeight: '20%'},
  maxH25: {maxHeight: '25%'},
  maxH30: {maxHeight: '30%'},
  maxH33: {maxHeight: '33%'},
  maxH40: {maxHeight: '40%'},
  maxH47: {maxHeight: '47.5%'},
  maxH50: {maxHeight: '50%'},
  maxH60: {maxHeight: '60%'},
  maxH65: {maxHeight: '65%'},
  maxH70: {maxHeight: '70%'},
  maxH75: {maxHeight: '75%'},
  maxH80: {maxHeight: '80%'},
  maxH85: {maxHeight: '85%'},
  maxH90: {maxHeight: '90%'},
  maxH100: {maxHeight: '100%'},

  rmstreach: {resizeMode: 'stretch'},
  rmcover: {resizeMode: 'cover'},
  rmcontain: {resizeMode: 'contain'},
  rmrepeat: {resizeMode: 'repeat'},
  rmcenter: {resizeMode: 'center'},

  ofcontain: {objectFit: 'contain'},
  ofcover: {objectFit: 'cover'},
  offill: {objectFit: 'fill'},
  ofscale: {objectFit: 'scale-down'},

  aic: {alignItems: 'center'},
  aife: {alignItems: 'flex-end'},
  aifs: {alignItems: 'flex-start'},

  jcfe: {justifyContent: 'flex-end'},
  jcfs: {justifyContent: 'flex-start'},
  jcc: {justifyContent: 'center'},
  jcsb: {justifyContent: 'space-between'},
  jcse: {justifyContent: 'space-evenly'},

  fdr: {flexDirection: 'row'},
  fdrr: {flexDirection: 'row-reverse'},
  fdc: {flexDirection: 'column'},
  fdcr: {flexDirection: 'column-reverse'},

  icon12: {
    height: moderateScale(12),
    width: moderateScale(12),
    objectFit: 'contain',
  },
  icon16: {
    height: moderateScale(16),
    width: moderateScale(16),
    objectFit: 'contain',
  },
  icon20: {
    height: moderateScale(20),
    width: moderateScale(20),
    objectFit: 'contain',
  },
  icon24: {
    height: moderateScale(24),
    width: moderateScale(24),
    objectFit: 'contain',
  },
  icon28: {
    height: moderateScale(28),
    width: moderateScale(28),
    objectFit: 'contain',
  },
  icon32: {
    height: moderateScale(32),
    width: moderateScale(32),
    objectFit: 'contain',
  },
  icon36: {
    height: moderateScale(36),
    width: moderateScale(36),
    objectFit: 'contain',
  },
  icon40: {
    height: moderateScale(40),
    width: moderateScale(40),
    objectFit: 'contain',
  },
  icon45: {
    height: moderateScale(45),
    width: moderateScale(45),
    objectFit: 'contain',
  },
  icon50: {
    height: moderateScale(50),
    width: moderateScale(50),
    objectFit: 'contain',
  },
  icon55: {
    height: moderateScale(55),
    width: moderateScale(55),
    objectFit: 'contain',
  },
  icon60: {
    height: moderateScale(60),
    width: moderateScale(60),
    objectFit: 'contain',
  },
  iconContainer12: {
    height: moderateScale(12),
    width: moderateScale(12),
  },
  iconContainer16: {
    height: moderateScale(16),
    width: moderateScale(16),
  },
  iconContainer20: {
    height: moderateScale(20),
    width: moderateScale(20),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer24: {
    height: moderateScale(24),
    width: moderateScale(24),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer28: {
    height: moderateScale(28),
    width: moderateScale(28),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer32: {
    height: moderateScale(32),
    width: moderateScale(32),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer36: {
    height: moderateScale(36),
    width: moderateScale(36),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer40: {
    height: moderateScale(40),
    width: moderateScale(40),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer45: {
    height: moderateScale(45),
    width: moderateScale(45),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer50: {
    height: moderateScale(50),
    width: moderateScale(50),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer55: {
    height: moderateScale(55),
    width: moderateScale(55),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer60: {
    height: moderateScale(60),
    width: moderateScale(60),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tdlu: {
    textDecorationLine: 'underline',
  },
  tdlt: {
    textDecorationLine: 'line-through',
  },
  tdln: {
    textDecorationLine: 'none',
  },
  tdlut: {
    textDecorationLine: 'underline line-through',
  },

  //----------------------------------Custom
  blurViewImage_round: {
    width: '100%',
    height: '100%',
    borderRadius: moderateScale(10),
    top: moderateScale(0),
    left: moderateScale(0),
    position: 'absolute',
    objectFit: 'cover',
  },
  blurViewImage: {
    width: '100%',
    height: '100%',
    top: moderateScale(0),
    left: moderateScale(0),
    position: 'absolute',
    objectFit: 'cover',
    resizeMode: 'cover',
  },
});
export default Css;
